owner: SRESchool
repo: AllMyhospitalnow-monitor-upptime
sites:
  - name: AskDoctorLive
    url: https://askdoctorlive.com
    ssl: true
  - name: BestCardiacHospitals
    url: https://bestcardiachospitals.com
    ssl: true
  - name: BestCosmeticHospitals
    url: https://bestcosmetichospitals.com
    ssl: true
  - name: BestDentalHospitals
    url: https://bestdentalhospitals.com
    ssl: true
  - name: BestEyeHospitals
    url: https://besteyehospitals.com
    ssl: true
  - name: BestHeartSurgery
    url: https://bestheartsurgery.com
    ssl: true
  - name: BestSpineHospitals
    url: https://bestspinehospitals.com
    ssl: true
  - name: CancersHospitals
    url: https://cancershospitals.com
    ssl: true
  - name: HeartCareForYou
    url: https://heartcareforyou.in
    ssl: true
  - name: HipHospitals
    url: https://hiphospitals.com
    ssl: true
  - name: KneeHospitals
    url: https://kneehospitals.com
    ssl: true
  - name: MyHospitalNow
    url: https://myhospitalnow.com
    ssl: true
  - name: MyMedicPlus
    url: https://mymedicplus.com
    ssl: true
  - name: SurgeryPlanet
    url: https://surgeryplanet.com
    ssl: true
    port: 80
    check: "tcp-ping"
    ipv6: true

assignees:
  - SRESchool

status-website:
  baseUrl: /AllMyhospitalnow-monitor-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Hospital Websites Uptime
  introTitle: "**Upptime** monitors hospital websites for uptime and SSL."
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/SRESchool/AllMyhospitalnow-monitor-upptime). No server required — just GitHub Actions, Issues, and Pages.

navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
